name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: change directory
      run: |
        cd tournaments
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'SOORAJ-SJ'
        reponame: 'vue-tournaments'
        token: ${{ secrets.GITHUB_TOKEN }}
