name: Build Vue
on: [push]
permissions: 
  contents: write
env: 
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
  VITE_GCP_KEY: ${{ secrets.VITE_GCP_KEY }}
  VITE_GOOGLE_SHEET_ID: ${{ secrets.VITE_GOOGLE_SHEET_ID }}
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install and build
        run: |
          cd tournaments
          npm ci
          npm run build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: 'tournaments/dist'
