name: Build Vue
on: [push]
permissions: 
  contents: write
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-page-prod
    env: 
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      VITE_GCP_KEY: ${{ secrets.VITE_GCP_KEY }}
      VITE_GOOGLE_SHEET_ID: ${{ secrets.VITE_GOOGLE_SHEET_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install and build
        run: |
          cd tournaments
          npm ci
          npm run build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: 'tournaments/dist'
      - name: Build success notification
        if: ${{ env.deployment_status == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: A new update have been deployed https://sooraj-sj.github.io/vue-tournaments/
      - name: Build skip notification
        if: ${{ env.deployment_status == 'skipped' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Skipped a deployment since there are no changes.
      - name: Build failure notification
        if: ${{ env.deployment_status == 'failed' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Deployment failed due to an unexpected error. Please check workflow runs for more info.
        
